### ISSUE TITLE
Perfil del usuario

### ISSUE THREAD

**Issue by pmarino2013** [marcosarias21/proyecto-clinica#37]
Cuando se da de alta el usuario no están bien validados los campos y tampoco tienen límite de caracteres lo que hace que se rompa el diseño del perfil de usuario.
![image](https://user-images.githubusercontent.com/35234004/182156367-94d3ffc8-6ea0-492c-8c1a-eaab4cd4e594.png)

**Comment by marcosarias21** [comment]
Perfecto , ya lo solucionaremos. Te tengo que avisar cuando lo hagamos?
Desde ya muchas gracias

**Comment by marcosarias21** [comment]
Hola ,  ya corregimos los errores. Saludos

**Comment by pmarino2013** [comment]
Listo, cierro el issue
